# This file tells NeoForge how to load embedded libraries at runtime
[[libraries]]
# The artifact to include
identifier = "io.javalin:javalin"
# The version of the artifact
version = "6.1.3"
# The path where it will be stored in the mod jar
path = "META-INF/jarjar/javalin-6.1.3.jar"

[[libraries]]
identifier = "com.fasterxml.jackson.core:jackson-databind"
version = "2.17.0"
path = "META-INF/jarjar/jackson-databind-2.17.0.jar"

[[libraries]]
identifier = "org.slf4j:slf4j-simple"
version = "2.0.9"
path = "META-INF/jarjar/slf4j-simple-2.0.9.jar"

[[libraries]]
identifier = "org.slf4j:slf4j-api"
version = "2.0.9"
path = "META-INF/jarjar/slf4j-api-2.0.9.jar"
